version: "3.9"
services:
  database:
    image: postgres:latest
    restart: always
    container_name: rolema_database
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_DEFAULT_PORT}"

