export default {
  NODE_ENV: String(process.env.NODE_ENV),
  ADMIN_API_PORT: Number(process.env.ADMIN_API_PORT),
  ADMIN_API_URL: String(process.env.NEXT_PUBLIC_ADMIN_API_ENDPOINT),
  AUTH_API_ENDPOINT: String(process.env.NEXT_PUBLIC_AUTH_API_ENDPOINT),
  AUTH_API_PORT: Number(process.env.AUTH_API_PORT),
  AUTH_PASSWORD: String(process.env.AUTH_PASSWORD),
  DB_URL: String(process.env.DB_URL),
  MAILER_EMAIL: String(process.env.MAILER_EMAIL),
  MAILER_PASSWORD: String(process.env.MAILER_PASSWORD),
  MAILER_SERVICE: String(process.env.MAILER_SERVICE),
  WEB_API_PORT: Number(process.env.WEB_API_PORT),
  WEB_API_URL: String(process.env.NEXT_PUBLIC_WEB_API_ENDPOINT),
  WEB_APP_URL: String(process.env.WEB_APP_URL),
  POSTGRES_HOST: String(process.env.POSTGRES_HOST),
  POSTGRES_PORT: Number(process.env.POSTGRES_PORT),
  POSTGRES_USER: String(process.env.POSTGRES_USER),
  POSTGRES_PASSWORD: String(process.env.POSTGRES_PASSWORD),
  POSTGRES_DB: String(process.env.POSTGRES_DB),
} as const;
